// Stripe Checkout for the demo storefront. The browser sends what is in the
// cart; every price is looked up here, in api/prices.json (generated by
// web/build.py from the very code path that renders the option buttons). A
// number typed into localStorage must never become a charge.
const PRICES = require('./prices.json');
const { stripeKey } = require('./_stripe');

const own = (o, k) => Object.prototype.hasOwnProperty.call(o, k);
const norm = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
const clean = (s) => String(s || '').replace(/<[^>]*>/g, '').trim().slice(0, 120);
const send = (res, status, obj) => {
  res.statusCode = status;
  res.end(JSON.stringify(obj));
};

module.exports = async (req, res) => {
  res.setHeader('Cache-Control', 'no-store');
  res.setHeader('Content-Type', 'application/json');
  try {
    if (req.method !== 'POST') return send(res, 405, { error: 'method' });
    const { key } = stripeKey();
    if (!key) return send(res, 500, { error: 'not configured' });

    let body = req.body;
    if (typeof body === 'string') { try { body = JSON.parse(body); } catch (e) { body = null; } }
    const lang = body && body.lang === 'en' ? 'en' : 'fr';
    const items = body && Array.isArray(body.items) ? body.items : [];
    if (!items.length || items.length > 20) return send(res, 400, { error: 'cart' });
    const site = 'https://' + (req.headers.host || 'www.meublesconfortstyles.com');

    const p = new URLSearchParams();
    p.set('mode', 'payment');
    p.set('locale', lang === 'fr' ? 'fr-CA' : 'en');
    p.set('success_url', site + (lang === 'fr' ? '/fr/merci/' : '/en/thank-you/') + '?sid={CHECKOUT_SESSION_ID}');
    p.set('cancel_url', site + '/' + lang + '/');
    p.append('shipping_address_collection[allowed_countries][]', 'CA');
    // Capture every buyer — guest or Link account — as a saved Stripe Customer,
    // and collect the fields GoHighLevel needs for the contact record.
    p.set('customer_creation', 'always');
    p.set('billing_address_collection', 'required');
    p.set('phone_number_collection[enabled]', 'true');
    p.set('metadata[lang]', lang);
    // Prices already include Québec TPS + TVQ — the figure on the page is the
    // figure charged. Automatic tax stays OFF on purpose: switching it on
    // would stack a second tax on top of one already in the amount.

    for (let n = 0; n < items.length; n++) {
      const it = items[n] || {};
      const id = String(it.id || '');
      const qty = Math.floor(Number(it.q));
      if (!own(PRICES, id) || !(qty >= 1 && qty <= 9)) return send(res, 400, { error: 'cart' });
      const prod = PRICES[id];
      // pv is the label of the chosen priced option. When the product has
      // options at more than one price, the label MUST resolve — falling back
      // to the base price would sell the expensive configuration cheap.
      const pvKey = norm(it.pv);
      let cents;
      if (own(prod.v, pvKey)) {
        cents = prod.v[pvKey];
      } else {
        const distinct = new Set(Object.keys(prod.v).map((k) => prod.v[k]));
        if (distinct.size > 1) return send(res, 400, { error: 'cart' });
        cents = prod.p;
      }
      if (!(cents >= 50)) return send(res, 400, { error: 'cart' });
      const opts = clean(it.opts);
      const name = (prod[lang] + (opts ? ' — ' + opts : '')).slice(0, 250);
      p.set(`line_items[${n}][quantity]`, String(qty));
      p.set(`line_items[${n}][price_data][currency]`, 'cad');
      // the amount already carries TPS + TVQ
      p.set(`line_items[${n}][price_data][tax_behavior]`, 'inclusive');
      p.set(`line_items[${n}][price_data][unit_amount]`, String(cents));
      p.set(`line_items[${n}][price_data][product_data][name]`, name);
      if (prod.img) p.append(`line_items[${n}][price_data][product_data][images][]`, prod.img);
    }

    const r = await fetch('https://api.stripe.com/v1/checkout/sessions', {
      method: 'POST',
      headers: {
        Authorization: 'Basic ' + Buffer.from(key + ':').toString('base64'),
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: p.toString(),
    });
    const d = await r.json().catch(() => null);
    if (!r.ok || !d || !d.url) return send(res, 502, { error: 'stripe' });
    return send(res, 200, { url: d.url });
  } catch (e) {
    return send(res, 500, { error: 'server' });
  }
};
